semi: truetabWidth: 2
printWidth: 120
singleQuote: true
trailingComma: all
arrowParens: always
endOfLine: lf
overrides:
  - files:
      - "**/*.yml"
      - "**/*.yaml"
    options:
      singleQuote: false
