CREATE DATABASE IF NOT EXISTS webprog;

USE webprog;
GRANT ALL PRIVILEGES ON *.* TO 'webprog'@'localhost' IDENTIFIED BY 'VgJUjBd8';
GRANT ALL PRIVILEGES ON *.* TO 'webprog'@'%' IDENTIFIED BY 'VgJUjBd8';

--GRANT ALL PRIVILEGES ON *.* TO 'webprog'@'localhost' IDENTIFIED BY '';
--GRANT ALL PRIVILEGES ON *.* TO 'webprog'@'%' IDENTIFIED BY '';